language: java
jdk:
  - oraclejdk8
script:
  - gradle clean check build -x checkstyleMain checkstyleTest
  - gradle clean fatJar -x checkstyleMain checkstyleTest
  - ./testjs.sh
  - ./rec dump rec-core/src/test/resources/caching.bin.test 3
